export interface Property {
  id: string;
  title: string;
  type: 'House' | 'Villa' | 'Apartment' | 'Plot';
  location: string;
  description: string;
  price: string;
  priceNumeric: number;
  image: string;
  area: string;
  areaNumeric: number;
  beds?: number;
  baths?: number;
  featured: boolean;
  new?: boolean;
  amenities: string[];
  postedDate: string;
  views?: number;
  listedDate?: string;
}

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Harmony House',
    type: 'House',
    location: 'Indiranagar, Bangalore',
    description: 'Beautiful modern house with all amenities',
    price: '₹1.2 Cr',
    priceNumeric: 12000000,
    image: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=1470&auto=format&fit=crop',
    area: '2000 sq ft',
    areaNumeric: 2000,
    beds: 3,
    baths: 2,
    featured: true, // This one is featured
    views: 1200, // This one is highly viewed
    listedDate: '2024-01-15', // Recent date
    amenities: ['Swimming Pool', 'Garden', 'Security']
  },
  {
    id: '2',
    title: 'Blissful Abode',
    type: 'Villa',
    location: 'Whitefield, Bangalore',
    description: 'Luxurious villa with modern amenities',
    price: '₹2.5 Cr',
    priceNumeric: 25000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1470&auto=format&fit=crop',
    area: '3500 sq ft',
    areaNumeric: 3500,
    beds: 4,
    baths: 3,
    featured: false, // This one is not featured
    views: 800, // This one is not highly viewed
    listedDate: '2024-01-01',
    amenities: ['Swimming Pool', 'Garden', 'Security']
  },
  {
    id: '3',
    title: 'Enchanted Villa',
    type: 'Villa',
    location: 'Koramangala, Bangalore',
    description: 'Premium villa with garden',
    price: '₹3.1 Cr',
    priceNumeric: 31000000,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1470&auto=format&fit=crop',
    area: '4000 sq ft',
    areaNumeric: 4000,
    beds: 5,
    baths: 4,
    featured: true,
    new: false,
    amenities: ['Swimming Pool', 'Garden', 'Security'],
    postedDate: '3 days ago'
  },
  {
    id: '4',
    title: 'Urban Nest',
    type: 'Apartment',
    location: 'HSR Layout, Bangalore',
    description: 'Modern apartment with city view',
    price: '₹90 L',
    priceNumeric: 9000000,
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1470&auto=format&fit=crop',
    area: '1200 sq ft',
    areaNumeric: 1200,
    beds: 2,
    baths: 2,
    featured: true,
    new: true,
    amenities: ['Gym', 'Security', 'Parking'],
    postedDate: '1 day ago'
  },
  {
    id: '5',
    title: 'Serene Plot',
    type: 'Plot',
    location: 'Sarjapur, Bangalore',
    description: 'Premium corner plot',
    price: '₹1.5 Cr',
    priceNumeric: 15000000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1632&auto=format&fit=crop',
    area: '2400 sq ft',
    areaNumeric: 2400,
    featured: true,
    new: true,
    amenities: ['Corner Plot', 'Ready for Construction'],
    postedDate: '5 days ago'
  },
  {
    id: '6',
    title: 'Golden Plot',
    type: 'Plot',
    location: 'Whitefield, Bangalore',
    description: 'Investment plot in prime location',
    price: '₹2.8 Cr',
    priceNumeric: 28000000,
    image: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?q=80&w=1470&auto=format&fit=crop',
    area: '3000 sq ft',
    areaNumeric: 3000,
    featured: true,
    new: false,
    amenities: ['Prime Location', 'Ready for Construction'],
    postedDate: '1 week ago'
  },
  {
    id: '7',
    title: 'Premium Corner Plot',
    type: 'Plot',
    location: 'Electronic City, Bangalore',
    description: 'Premium corner plot in gated community',
    price: '₹1.8 Cr',
    priceNumeric: 18000000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1632&auto=format&fit=crop',
    area: '2800 sq ft',
    areaNumeric: 2800,
    featured: true,
    new: false,
    amenities: ['Corner Plot', 'Gated Community', 'All Utilities'],
    postedDate: '3 days ago'
  },
  {
    id: '8',
    title: 'Investment Plot',
    type: 'Plot',
    location: 'Devanahalli, Bangalore',
    description: 'High-potential investment plot near airport',
    price: '₹2.2 Cr',
    priceNumeric: 22000000,
    image: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?q=80&w=1470&auto=format&fit=crop',
    area: '3200 sq ft',
    areaNumeric: 3200,
    featured: true,
    new: true,
    amenities: ['Near Airport', 'High ROI', 'Clear Title'],
    postedDate: '1 week ago'
  },
  {
    id: '9',
    title: 'Commercial Plot',
    type: 'Plot',
    location: 'Hebbal, Bangalore',
    description: 'Prime commercial plot suitable for retail or office development',
    price: '₹3.2 Cr',
    priceNumeric: 32000000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1632&auto=format&fit=crop',
    area: '5000 sq ft',
    areaNumeric: 5000,
    featured: true,
    new: false,
    amenities: ['Main Road Access', 'Commercial Zone', 'All Utilities'],
    postedDate: '2 weeks ago'
  },
  {
    id: '10',
    title: 'Residential Plot',
    type: 'Plot',
    location: 'Yelahanka, Bangalore',
    description: 'Ready-to-build residential plot in prime location',
    price: '₹1.5 Cr',
    priceNumeric: 15000000,
    image: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?q=80&w=1470&auto=format&fit=crop',
    area: '2400 sq ft',
    areaNumeric: 2400,
    featured: true,
    new: true,
    amenities: ['Residential Zone', 'Ready for Construction', 'Clear Title'],
    postedDate: '4 days ago'
  },
  {
    id: '11',
    title: 'Skyline Heights',
    type: 'Apartment',
    location: 'MG Road, Bangalore',
    description: 'High-rise apartment with panoramic city views',
    price: '₹1.75 Cr',
    priceNumeric: 17500000,
    image: 'https://images.unsplash.com/photo-1572120360610-d971b9b1d08b?q=80&w=1470&auto=format&fit=crop',
    area: '1500 sq ft',
    areaNumeric: 1500,
    beds: 3,
    baths: 2,
    featured: true,
    new: true,
    amenities: ['Gym', 'Rooftop Garden', 'Clubhouse'],
    postedDate: '1 day ago'
  },
  {
    id: '12',
    title: 'Luxury Villa',
    type: 'Villa',
    location: 'Banashankari, Bangalore',
    description: 'Luxury villa with pool and garden',
    price: '₹4.5 Cr',
    priceNumeric: 45000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1470&auto=format&fit=crop',
    area: '5000 sq ft',
    areaNumeric: 5000,
    beds: 6,
    baths: 4,
    featured: true,
    new: false,
    amenities: ['Swimming Pool', 'Garden', 'Security'],
    postedDate: '2 weeks ago'
  },
  {
    id: '13',
    title: 'Modern Apartment',
    type: 'Apartment',
    location: 'Koramangala, Bangalore',
    description: 'Modern apartment with city view',
    price: '₹1.5 Cr',
    priceNumeric: 15000000,
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1470&auto=format&fit=crop',
    area: '1000 sq ft',
    areaNumeric: 1000,
    beds: 2,
    baths: 2,
    featured: true,
    new: true,
    amenities: ['Gym', 'Security', 'Parking'],
    postedDate: '3 days ago'
  },
  {
    id: '14',
    title: 'Cozy Cottage',
    type: 'House',
    location: 'Jayanagar, Bangalore',
    description: 'Cozy cottage with garden',
    price: '₹1.8 Cr',
    priceNumeric: 18000000,
    image: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=1470&auto=format&fit=crop',
    area: '1800 sq ft',
    areaNumeric: 1800,
    beds: 3,
    baths: 2,
    featured: true,
    new: false,
    amenities: ['Garden', 'Security'],
    postedDate: '1 week ago'
  },
  {
    id: '15',
    title: 'Luxury Plot',
    type: 'Plot',
    location: 'Sarjapur, Bangalore',
    description: 'Luxury plot in prime location',
    price: '₹3.5 Cr',
    priceNumeric: 35000000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1632&auto=format&fit=crop',
    area: '4000 sq ft',
    areaNumeric: 4000,
    featured: true,
    new: true,
    amenities: ['Prime Location', 'Ready for Construction'],
    postedDate: '2 weeks ago'
  },
  {
    id: '16',
    title: 'Investment Property',
    type: 'Plot',
    location: 'Whitefield, Bangalore',
    description: 'Investment property in prime location',
    price: '₹2.5 Cr',
    priceNumeric: 25000000,
    image: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?q=80&w=1470&auto=format&fit=crop',
    area: '3500 sq ft',
    areaNumeric: 3500,
    featured: true,
    new: false,
    amenities: ['Prime Location', 'Ready for Construction'],
    postedDate: '1 week ago'
  },
  {
    id: '17',
    title: 'Luxury Villa',
    type: 'Villa',
    location: 'Banashankari, Bangalore',
    description: 'Luxury villa with pool and garden',
    price: '₹4.5 Cr',
    priceNumeric: 45000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1470&auto=format&fit=crop',
    area: '5000 sq ft',
    areaNumeric: 5000,
    beds: 6,
    baths: 4,
    featured: true,
    new: false,
    amenities: ['Swimming Pool', 'Garden', 'Security'],
    postedDate: '2 weeks ago'
  },
  {
    id: '18',
    title: 'Modern Apartment',
    type: 'Apartment',
    location: 'Koramangala, Bangalore',
    description: 'Modern apartment with city view',
    price: '₹1.5 Cr',
    priceNumeric: 15000000,
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1470&auto=format&fit=crop',
    area: '1000 sq ft',
    areaNumeric: 1000,
    beds: 2,
    baths: 2,
    featured: true,
    new: true,
    amenities: ['Gym', 'Security', 'Parking'],
    postedDate: '3 days ago'
  },
  {
    id: '19',
    title: 'Cozy Cottage',
    type: 'House',
    location: 'Jayanagar, Bangalore',
    description: 'Cozy cottage with garden',
    price: '₹1.8 Cr',
    priceNumeric: 18000000,
    image: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=1470&auto=format&fit=crop',
    area: '1800 sq ft',
    areaNumeric: 1800,
    beds: 3,
    baths: 2,
    featured: true,
    new: false,
    amenities: ['Garden', 'Security'],
    postedDate: '1 week ago'
  },
  {
    id: '20',
    title: 'Luxury Plot',
    type: 'Plot',
    location: 'Sarjapur, Bangalore',
    description: 'Luxury plot in prime location',
    price: '₹3.5 Cr',
    priceNumeric: 35000000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1632&auto=format&fit=crop',
    area: '4000 sq ft',
    areaNumeric: 4000,
    featured: true,
    new: true,
    amenities: ['Prime Location', 'Ready for Construction'],
    postedDate: '2 weeks ago'
  },
  {
    id: '21',
    title: 'Investment Property',
    type: 'Plot',
    location: 'Whitefield, Bangalore',
    description: 'Investment property in prime location',
    price: '₹2.5 Cr',
    priceNumeric: 25000000,
    image: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?q=80&w=1470&auto=format&fit=crop',
    area: '3500 sq ft',
    areaNumeric: 3500,
    featured: true,
    new: false,
    amenities: ['Prime Location', 'Ready for Construction'],
    postedDate: '1 week ago'
  },
  {
    id: '22',
    title: 'Luxury Villa',
    type: 'Villa',
    location: 'Banashankari, Bangalore',
    description: 'Luxury villa with pool and garden',
    price: '₹4.5 Cr',
    priceNumeric: 45000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1470&auto=format&fit=crop',
    area: '5000 sq ft',
    areaNumeric: 5000,
    beds: 6,
    baths: 4,
    featured: true,
    new: false,
    amenities: ['Swimming Pool', 'Garden', 'Security'],
    postedDate: '2 weeks ago'
  },
  {
    id: '23',
    title: 'Modern Apartment',
    type: 'Apartment',
    location: 'Koramangala, Bangalore',
    description: 'Modern apartment with city view',
    price: '₹1.5 Cr',
    priceNumeric: 15000000,
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1470&auto=format&fit=crop',
    area: '1000 sq ft',
    areaNumeric: 1000,
    beds: 2,
    baths: 2,
    featured: true,
    new: true,
    amenities: ['Gym', 'Security', 'Parking'],
    postedDate: '3 days ago'
  },
  {
    id: '24',
    title: 'Cozy Cottage',
    type: 'House',
    location: 'Jayanagar, Bangalore',
    description: 'Cozy cottage with garden',
    price: '₹1.8 Cr',
    priceNumeric: 18000000,
    image: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=1470&auto=format&fit=crop',
    area: '1800 sq ft',
    areaNumeric: 1800,
    beds: 3,
    baths: 2,
    featured: true,
    new: false,
    amenities: ['Garden', 'Security'],
    postedDate: '1 week ago'
  },
  {
    id: '25',
    title: 'Luxury Plot',
    type: 'Plot',
    location: 'Sarjapur, Bangalore',
    description: 'Luxury plot in prime location',
    price: '₹3.5 Cr',
    priceNumeric: 35000000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1632&auto=format&fit=crop',
    area: '4000 sq ft',
    areaNumeric: 4000,
    featured: true,
    new: true,
    amenities: ['Prime Location', 'Ready for Construction'],
    postedDate: '2 weeks ago'
  },
  {
    id: '26',
    title: 'Investment Property',
    type: 'Plot',
    location: 'Whitefield, Bangalore',
    description: 'Investment property in prime location',
    price: '₹2.5 Cr',
    priceNumeric: 25000000,
    image: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?q=80&w=1470&auto=format&fit=crop',
    area: '3500 sq ft',
    areaNumeric: 3500,
    featured: true,
    new: false,
    amenities: ['Prime Location', 'Ready for Construction'],
    postedDate: '1 week ago'
  },
  {
    id: '27',
    title: 'Luxury Villa',
    type: 'Villa',
    location: 'Banashankari, Bangalore',
    description: 'Luxury villa with pool and garden',
    price: '₹4.5 Cr',
    priceNumeric: 45000000,
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1470&auto=format&fit=crop',
    area: '5000 sq ft',
    areaNumeric: 5000,
    beds: 6,
    baths: 4,
    featured: true,
    new: false,
    amenities: ['Swimming Pool', 'Garden', 'Security'],
    postedDate: '2 weeks ago'
  },
  {
    id: '28',
    title: 'Modern Apartment',
    type: 'Apartment',
    location: 'Koramangala, Bangalore',
    description: 'Modern apartment with city view',
    price: '₹1.5 Cr',
    priceNumeric: 15000000,
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1470&auto=format&fit=crop',
    area: '1000 sq ft',
    areaNumeric: 1000,
    beds: 2,
    baths: 2,
    featured: true,
    new: true,
    amenities: ['Gym', 'Security', 'Parking'],
    postedDate: '3 days ago'
  },
  {
    id: '29',
    title: 'Cozy Cottage',
    type: 'House',
    location: 'Jayanagar, Bangalore',
    description: 'Cozy cottage with garden',
    price: '₹1.8 Cr',
    priceNumeric: 18000000,
    image: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=1470&auto=format&fit=crop',
    area: '1800 sq ft',
    areaNumeric: 1800,
    beds: 3,
    baths: 2,
    featured: true,
    new: false,
    amenities: ['Garden', 'Security'],
    postedDate: '1 week ago'
  },
  {
    id: '30',
    title: 'Luxury Plot',
    type: 'Plot',
    location: 'Sarjapur, Bangalore',
    description: 'Luxury plot in prime location',
    price: '₹3.5 Cr',
    priceNumeric: 35000000,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1632&auto=format&fit=crop',
    area: '4000 sq ft',
    areaNumeric: 4000,
    featured: true,
    new: true,
    amenities: ['Prime Location', 'Ready for Construction'],
    postedDate: '2 weeks ago'
  },
  {
    id: 'land1',
    type: 'Plot',
    title: 'Premium Plot in Whitefield',
    location: 'Whitefield, Bangalore',
    price: '₹80 Lac',
    priceNumeric: 8000000,
    area: '1200 sq ft',
    areaNumeric: 1200,
    featured: true,
    views: 800, // Will show Featured tag
    listedDate: '2024-01-20',
    description: 'Premium corner plot in gated community',
    amenities: ['Corner Plot', 'Gated Community']
  },
  {
    id: 'land2',
    type: 'Plot',
    title: 'Commercial Plot',
    location: 'Electronic City, Bangalore',
    price: '₹1.5 Cr',
    priceNumeric: 15000000,
    area: '2000 sq ft',
    areaNumeric: 2000,
    featured: true,
    views: 1500, // Will show Most Viewed tag instead of Featured
    listedDate: '2024-01-15',
    description: 'Prime commercial plot',
    amenities: ['Commercial Zone', 'Main Road']
  }
  // Add more properties as needed...
];








